on:
  push:
    branches: ["main"]
name: 🚀 Deploy website on push

jobs:
  build:
    name: ⚙️ Build
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
